theme: jekyll-theme-minimal
title: Excel Datasource
logo: /src/img/logo.png
description: Load csv/excel files data into grafana's dashboards from SFTP servers

show_downloads: true
google_analytics:
