theme: jekyll-theme-minimal
title: BMC Excel datasource
description: Load csv/excel files data into grafana's dashboards from SFTP servers


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
