theme: jekyll-theme-minimal
title: BMC Excel datasource
image: /src/img/logo.png
description: Load csv/excel files data into grafana's dashboards from SFTP servers

twitter_username: bujupah
github_username: bujupah
author: khalil.mejdi97@gmail.com
